### ISSUE TITLE
add mapMutations style helper to pathify

### ISSUE THREAD

**Issue by mxlnk** [davestewart/vuex-pathify#11]
# Example of the Problem
In my store I have:

```
state: {
  someBool: true,
}

mutations: {
  TOGGLE_BOOL(state) {
    state.someBool = !state.someBool;
  },
}
```
Or take the increment example for that sake.

Now I want to call these from a component, if I read the docu correctly, direct access would be recommended, so I would have to:
```
methods: {
  toggleBool() {
    this.$store.set('TOGGLE_BOOL!');
  }
}
```
# Solution
I'd want to be able map the mutations to local functions, like suggested in https://github.com/davestewart/vuex-pathify/issues/5 for actions.

Do you see value in this?
I could of course go and use vuex's mapMutations, what I prefer about having the helper in pathify is, that I could then refrain from using vuex helpers at all, which would decrease the likelihood of someone new on the project also using the vuex helpers for getState, because I want them to use get and sync.

Or are my mutations actions in your mind?

Actually my first try was to go:
```
methods: {
  ...set({
    toggleBool: 'TOGGLE_BOOL',
  }),
}
```
Maybe, that could be an interface for actions and mutations?

**Comment by davestewart** [comment]
The main reason for the mapActions helper by the way, was import convenience:

```js
import { get, sync, mapActions } from 'vuex-pathify'
```
vs:
```js
import { get, sync } from 'vuex-pathify'
import { mapActions } from 'vuex'
```

The thing is, the vuex `mapMutations` helper already does what you want.

**Comment by mxlnk** [comment]
Yes good point. I would agree that it is hard come up with many useful custom mutations. Another one might be an increment mutation.

For me the main reason of wanting it is basically also import convenience.

Thanks for the toggle "workaround" though, I can also live/work with that, but would somehow still slightly prefer the mutation I think.

**Comment by davestewart** [comment]
> Or take the increment example for that sake.

Ahh... just re-read and now I see your motivation.

I think this kind of mapping would probably muddy the core concept of Pathify. I'll explain why.

The core concept of Pathify is to transparently map a state-based path to Vuex read / write. This works best for 1:1 set / get operations, such as `someBool`. Non 1:1 operations, such as `toggleBool` sit outside of this paradigm, hence the direct syntax:

```js
set('toggleBool!')
```

The problem (as I see it) with the direct syntax is often it's semantically incorrect - it's less of a "set" and more of a "call", "do" or "exec".

I was toying with the idea of a `call` helper, which could be used in this situation:

```
call('toggleBool')
```

But I decided to let things settle before adding features.

So adding a mapMutations helper whilst an interesting idea, starts to pull Pathify into a kind of utility library for Vuex, when an actual utility library for Vuex would probably be a better fit!

By the way you can also use the `commit` convenience helper if you need it:

```
import { get, set, commit } from 'vuex-pathify'

commit('toggleBool')
``` 

https://github.com/davestewart/vuex-pathify/blob/develop/src/helpers/vuex.js

**Comment by davestewart** [comment]
> Maybe, that could be an interface for actions and mutations?

```js
methods: {
  ...set({
    toggleBool: 'TOGGLE_BOOL',
  }),
}
```

It would be cool if so, but the function would need to return very different blocks:

```
// mutation:
{ get(), set() }

// action
() => dispatch()
```

I'll close this now, but will probably think a bit more about it :)

**Comment by davestewart** [comment]
@mxlnk thought you would like to know I added the `call()` helper in the end:

https://davestewart.github.io/vuex-pathify/#/api/component?id=call
