### ISSUE TITLE
 Unable to expand wildcard path Nuxt Js

### ISSUE THREAD

**Issue by sinangulsever** [davestewart/vuex-pathify#111]
**Unable to expand wildcard path**  'userbilgi/*':

Nuxt component 
![image](https://user-images.githubusercontent.com/5988390/92382883-07c2c180-f116-11ea-9feb-9659686f9273.png)

Store folder
![image](https://user-images.githubusercontent.com/5988390/92382944-25902680-f116-11ea-912a-49160512af56.png)

Store module 
![image](https://user-images.githubusercontent.com/5988390/92383050-553f2e80-f116-11ea-828f-7f0c4ffe7de7.png)

Console error
![image](https://user-images.githubusercontent.com/5988390/92383076-5ff9c380-f116-11ea-89a5-b04b74c4d79c.png)

Why does this problem occur?

**Comment by davestewart** [comment]
Hey. Did you check the order of your store and router imports as the error suggests?

**Comment by sinangulsever** [comment]
**"  - Make sure the store is imported before the router, then reload"**
how can i do this in nuxt js

**Comment by sinangulsever** [comment]
Vuex

![image](https://user-images.githubusercontent.com/5988390/92383648-66d50600-f117-11ea-9f2a-7ab0b229cd01.png)

**Comment by davestewart** [comment]
Oh crap, I forgot about Nuxt!

Not 100% sure about this one (it's been a long time since I looked at the source) but can you try making the module and its calls, namespaced? Do you know how to do that?

PS. easier to post real code then I can make alterations and post back.

**Comment by davestewart** [comment]
OK - it seems this might b a bug in Nuxt that is still not fixed:

- https://github.com/nuxt/nuxt.js/issues/5405#issuecomment-666324819

The solution is to NOT use wildcards.

This will make your code clearer, anyway.

Wildcards are useful, mainly for large options sets, but better to make your code explicit.

**Comment by sinangulsever** [comment]
I removed the wildcard characters.
![image](https://user-images.githubusercontent.com/5988390/92384928-a3096600-f119-11ea-8003-87855851623e.png)

Component 
![image](https://user-images.githubusercontent.com/5988390/92385014-c9c79c80-f119-11ea-82e1-e984ba123208.png)


This time it gave a different error
![image](https://user-images.githubusercontent.com/5988390/92384964-b1578200-f119-11ea-9ec1-a64877553de6.png)

**Comment by davestewart** [comment]
Ah, sorry... you will need to specify the properties manually (rather than using the `*` character, which effectively says "please get all properties"), so:

```
sync('userbilgi', [
  'name',
  'lastname',
])
```
