### ISSUE TITLE
require('vue-class-component') breaks bundle

### ISSUE THREAD

**Issue by johannes-z** [davestewart/vuex-pathify#116]
**Describe the bug**
I'm bundling a library as UMD that uses vuex-pathify. This line breaks the build however:

`var createDecorator$1 = require('vue-class-component').createDecorator;`

This should be an `import`-statement inside the .esm build, I guess. See https://unpkg.com/browse/vuex-pathify@1.4.1/dist/vuex-pathify.esm.js Line 1100.

**Expected behaviour**
I'm already using `vue-class-component` in my bundle. This should not break my build.

**Additional context**
This probably only works in a cjs environment, not UMD/AMD.

Fixing version to `1.2.0` creates a working bundle. Every newer version breaks it.

**Comment by davestewart** [comment]
Hey Johannes.

Sorry about this.

Vue Class Component was added by a contributor to support Vuex Pathify decorators for vue-class-component.

At the time I was super-busy and hadn't used vue-class-component. There was some discussion around it here:

- https://github.com/davestewart/vuex-pathify/issues/50

Eventually, this PR was the one that added it:

- https://github.com/davestewart/vuex-pathify/pull/57

I'm happy to take a look at this again now, perhaps involve in original collaborator; it may be that I know more than I did then.

Do you have any thoughts on what would be a good way to move forward?

**Comment by johannes-z** [comment]
Shouldnt changing this line:

`const createDecorator = require('vue-class-component').createDecorator` (https://github.com/davestewart/vuex-pathify/blob/master/src/helpers/decorators.js#L18)

to this:

`import { createDecorator } from 'vue-class-component'`

fix the issue? This way the dependency will actually be added in the final bundle.

**Comment by davestewart** [comment]
My expertise in how webpack does its thing is not good enough to know if that will do the job, but you can have a crack yourself if you like.

You can use `npm link` to make this pretty easy:

- fork this repo
- make the changes
- run `npm run build` to build the source in the pathify folder
- run `npm link` to set up the link from the pathify folder
- run `npm link vuex-pathify` from your project folder to point the pathify dependency to your local folder

Want to try?

to test it out.

**Comment by johannes-z** [comment]
Sure I'll try. I'll come back to you when I have results.

**Comment by johannes-z** [comment]
I just tested it. It worked when I changed it to an import statement. I've opened a PR.

**Comment by davestewart** [comment]
Good man!

I'm a little stacked for the next few days, but I will get to it.

You can use your link in the meantime.

If I haven't got to it by next week, bug me here :)

**Comment by johannes-z** [comment]
ping @davestewart
