### ISSUE TITLE
Sync/set doesn't work with actions in nested properties in module

### ISSUE THREAD

**Issue by acan13** [davestewart/vuex-pathify#13]
The sync and set component helpers don't work for nested properties in a module if you use actions.

Here's an example of everything working using only make.mutations:
https://codesandbox.io/s/n72lj3v9j0

Here's the exact same code except with the addition of make.actions:
https://codesandbox.io/s/889r80j7j

Basically, trying to use actions with a nested property in a module doesn't work. It _does_ work if you only use mutations, or with actions if the property isn't nested, or if it's nested but it's not in a module.

**Comment by davestewart** [comment]
Hey, nice one. I can confirm that this has unexpected behaviour.

It looks like it's actually setting the `myData` property rather than `myData.<propName>`.

I'll take a look at this hopefully today.

Thanks for finding this!

**Comment by timeslicelive** [comment]
OK, fixed in release v1.0.9.

Not sure why your demo won't show that, maybe CS is not picking up on the new version, but this fork with version update shows it working fine:

https://codesandbox.io/s/lp1917p4o7

**Comment by davestewart** [comment]
OK, fixed in release v1.0.9.

Not sure why your demo won't show that, maybe CS is not picking up on the new version, but this fork with version update shows it working fine:

- https://codesandbox.io/s/lp1917p4o7
