### ISSUE TITLE
Set function isn't exposed

### ISSUE THREAD

**Issue by LanFeusT23** [davestewart/vuex-pathify#15]
The documentation shows `store.set('loaded', true)` but the `main.js` file does not expose any set method.

Currently I'm having to use `mapMutations` in order to set a state value.

**Comment by davestewart** [comment]
The plugin patches the store instance with the `set` method.

Can you show some actual code?

**Comment by LanFeusT23** [comment]
Oh I see... I was kind of expecting the same behaviour as the `get` method. Being able to export set and use it directly without going through the store, just like the get method.

Thanks.

**Comment by davestewart** [comment]
Ah, are you sure you don't mean the *component helper* `get` ?

Set was defined for a while, but then I realised there's not really any practical use for it in components. When would set but not get?

**Comment by davestewart** [comment]
> I thought it'd be nice if I could do just set(...)

Yeah, Vue's computed properties don't work like that, you would need to call a method as you say :)
