### ISSUE TITLE
Vue CLI 3 Plugin?

### ISSUE THREAD

**Issue by patrickcate** [davestewart/vuex-pathify#17]
I'd love to see this available as a Vue CLI 3 plugin. Are there any plans for this?

**Comment by davestewart** [comment]
Hey Patrick,

I know about Vue CLI 3, but I don't know about plugins, or how this could be made into a plugin!

Can you give me the lowdown?

What would the plugin do?

**Comment by patrickcate** [comment]
Hi Dave,

Vue CLI 3 allows for third-party functionality to be added to a Vue CLI project via the `vue add` command or via the new UI launched from the `vue ui` command.

Here are the docs for cli plugin authors: 
https://cli.vuejs.org/dev-guide/plugin-dev.html
https://cli.vuejs.org/dev-guide/ui-info.html
https://cli.vuejs.org/dev-guide/ui-api.html

The UI mode is particularly cool because it can provide a configuration page where users can easily select any options available for the plugin. I could see this being very useful for choosing the Vuex Pathify schema config. 

If you install the latest version of Vue CLI 3, in UI mode the ESLint plugin provides a great example of this.

![screen shot 2018-06-16 at 7 47 59 am](https://user-images.githubusercontent.com/6277206/41498365-be6a6898-7139-11e8-83dd-1efdafb312bc.png)

**Comment by davestewart** [comment]
But these are plugins for cli processes, no?

**Comment by patrickcate** [comment]
Vue CLI plugins aren't limited to just that. Through generators they can add libraries, add/change files, setup configuration, etc.

**Here are some examples of third-card plugins:**

1. https://github.com/vuetifyjs/vue-cli-plugin-vuetify
2. https://github.com/Akryum/vue-cli-plugin-apollo
3. https://github.com/Seb-L/vue-cli-plugin-element-ui
4. https://github.com/vuetifyjs/vue-cli-plugin-vuetify
5. https://github.com/quasarframework/vue-cli-plugin-quasar
6. https://github.com/komushi/vue-cli-plugin-appsync
7. https://github.com/paulgv/vue-cli-plugin-vuex-module-generator
8. https://github.com/raphaelcockx/vue-cli-plugin-meta

**Comment by davestewart** [comment]
Hmmm
