### ISSUE TITLE
Wildcard + custom getters.

### ISSUE THREAD

**Issue by Michelemassari** [davestewart/vuex-pathify#2]
Hello, I have the following (demo) state:

```javascript
const state = {
  name: 'John Doe',
  count: 0,
  loading: false,
  redditPosts: [],
  getRedditPostsError: [],
  locale: 'en'
}
```

and the following getters:

```javascript
import { make } from 'vuex-pathify' // https://davestewart.github.io/vuex-pathify/#/api/store?id=make-getters

const getters = {

  fibonacciNumber (state) {
    const fibonacci = (number) => {
      if (number < 1) return 0
      if (number <= 2) return 1
      return fibonacci(number - 1) + fibonacci(number - 2)
    }

    return fibonacci(state.count)
  },
  redditTopPostTitle (state) {
    return state.redditPosts.length ? state.redditPosts[0].data.title : 'Loading...'
  },
  redditTopPostUrl (state) {
    return state.redditPosts.length ? `https://www.reddit.com${state.redditPosts[0].data.permalink}` : '#'
  },
  ...make.getters(state)
}
```

In my component, when I call the function to map all getters with a wildcard
```javascript
computed: {
    ...get('demo@*')
  }
```
I only receive the standard getters (the ones generated with `make`) and not my custom ones.

Is there something I'm missing?

**Comment by davestewart** [comment]
Hmmm...

Is demo a module? If so, should it be namespaced?

Either way, the `@` syntax is used to access store **sub-properties**:

```
// store
const state = {
    value: 1,
    options: {
        value: 1,
    }
}

// component
computed: {
    value: get('value'),
    optionValue: get('options@value')
}
```

This being the case, you just won't need `@`. If you just use the following, you should be good:

```js
// not namespaced
...get('*')

// namespaced
...get('demo/*')
```
Let me know if that helps.

> I only receive the standard getters (the ones generated with make) and not my custom ones.

That's a bit weird though - I'll investigate!

**Comment by Michelemassari** [comment]
In this particular case it is.
I am creating a project-starter for my agency and the demo module is supposed to help/guide in the creation of the application 😄 

I managed to get the generated properties by using `...get('demo/*')` but I'm still missing the Custom ones like fibonacciNumber, redditTopPostTitle, etc.

Thanks for investigating and for this awesome tool!
Please let me know if I can help.

**Comment by davestewart** [comment]
> I'm still missing the Custom ones like fibonacciNumber, redditTopPostTitle, etc.

OK. let me investigate.

By the way, you don't need to create "redundant" getters!

Pathify automatically pulls from state if it doesn't find a getter. This is called [Accessor Priority](https://davestewart.github.io/vuex-pathify/#/api/properties?id=accessor-priority) and is designed to keep your stores lean. 

The only reason `make.getters()` is included is for folks who really REALLY want to make getters for everything.

They don't need to though - Pathify's paths provides the consistency, rather than making redundant getters and actions :)

**Comment by davestewart** [comment]
OK, this is a bug. I'll get a fix out tonight!
