### ISSUE TITLE
call() seems like not return the promise as vuex mapActions 

### ISSUE THREAD

**Issue by maimake** [davestewart/vuex-pathify#25]
The Component helper fun `call()` should create functions which should be return promise as `mapActions`, Thx

**Comment by davestewart** [comment]
So what is currently happening, and what did you want to happen, and why? How is it different from mapActions?

Can you outline your use-cases with example code?

**Comment by traherom** [comment]
I ran into this today. Some portions of code:

```javascript
methods: {
    ...call([
      'benchmarks/loadBenchmarks',
      // 'data/loadScan', // Using this will cause the .then to fail in onSelectScan
    ]),
    ...mapActions('data', [
      'loadScan', // This will work properly though
    ]),

    onSelectScan(side, scan) {
      // Fully load scan
      this.loadScan({ id: scan.pk, truncate: true }).then(scan => {
        if(side === 'old')
          this.oldScan = scan;
        else
          this.newScan = scan;

        this.loadBenchmarks({ benchmarkIds: scan.benchmark_ids });
      });
    },
}
```

I believe all it takes to fix this changing https://github.com/davestewart/vuex-pathify/blob/892e2403794521c4dcd18242932768dbb21bc6de/src/helpers/component.js#L152 to be `return this.$store.dispatch(path, value)`. According to https://vuex.vuejs.org/guide/actions.html#composing-actions, this returning a Promise thing is the normal vuex action behavior. 

I can submit a PR if needed. I just started using Pathify, but it's great so far!

**Comment by davestewart** [comment]
Fixes 03079f458afda39a3524816b3f785ae05c9c1762

**Comment by davestewart** [comment]
See: https://github.com/davestewart/vuex-pathify/commit/03079f458afda39a3524816b3f785ae05c9c1762

**Comment by kae24** [comment]
waiting for this

**Comment by traherom** [comment]
There's an issue with getting it published (see discussion on the commit). For now, just use `mapActions()`. It'll be a drop-in replacement once updated.

**Comment by maimake** [comment]
@davestewart Can not be fixed ?

**Comment by davestewart** [comment]
Sorry for the wait, working very long days right now! Let me get in touch with NPM and see what they say

**Comment by davestewart** [comment]
OK, I think I must have been patching and building in the wrong order. I've just checked [unpkg](https://unpkg.com/vuex-pathify@1.1.3/dist/vuex-pathify.js) and it looks like it has published correctly!

**Comment by traherom** [comment]
Confirmed working for me now. Thanks!
