### ISSUE TITLE
Sub-property access in a normalized store

### ISSUE THREAD

**Issue by emcho92** [davestewart/vuex-pathify#27]
I have a setup where my store only holds normalized data, so no nested objects, everything is referenced to each other via ids. How do I use the path syntax in this case then.

An example of normalized store state of a couple of modules:
```
const posts = {
  "1": {
    id: 1,
    title: "Test",
    author: 1
  },
  "2": {
    id: 2,
    title: "Post",
    author: 2
  }
};

const authors = {
 "1": {
    id: 1,
    name: "Joe"
  },
  "2": {
    id: 2,
    name: "Jack"
  }
};
```

So say these modules are the children of a parent **entity** module. 
Now, if I want to use the path syntax to sync a certain post property, in my Post component, where the post id is dynamic, I need this:

```
export default {
  props: {  
    postId: Number  
  },  
  computed: {  
    title: sync(`entity/posts@{this.postId}.title`)  
  }  
};
```

I can't seem to access `this` is the sync property, and I need it since the first sub-properties in the module are the number keys. Any workarounds?

**Comment by davestewart** [comment]
You look like you are missing the `$` from that example, but this is because you're accessing `this` at the time you are declaring the component - so there cannot be a this :)

I think you could potentially do this in the component `created` method though?

```js
created () {
  const computed = {  
    title: sync(`entity/posts@{this.postId}.title`)  
  }  
  Object.assign(this.$options.computed, computed) 
}
```

Try along those lines of a variation of. You may need to check that computed is an object before assigning!

**Comment by emcho92** [comment]
Thanks, that works, and the title is rendered now, but this error also shows in the console:

`[Vue warn]: Property or method "title" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property` 

...as if the title is not even defined. Is it tied to the lifecycle somehow?

**Comment by davestewart** [comment]
That's annoying.

What about `beforeCreated` ?

You may need to use `this.$options.propsData.postId`

**Comment by emcho92** [comment]
I tried `beforeCreate` earlier, didn't work, but coupled with `this.$options.propsData.postId` it does, awesome :) I now see how much info there is in the api docs of the vue instance, definitely need to look into it more. Thanks! 
Awesome library btw, I'm setting it up in an already existing project, where I want to minimize boilerplate and make things simpler. I'm bound to run into more things like this so thanks for helping out, I hope these scenarios prove useful for other people too.

**Comment by emcho92** [comment]
Mind giving an example, can't find anything in the docs, and this doesn't work:

```
...

get("entity/post/getPostById", 1)

...
```

```
getPostById: (state) => (id) => {
    return state.posts.find(post => post.id === id);
}
```

**Comment by davestewart** [comment]
Good point, I guess I should add some examples.

Did you try using `get()` in your methods block? Getter methods are really functions, after all.

**Comment by davestewart** [comment]
OK, I checked this out.

The store accessor functionality allows for getter functions out of the box:

https://davestewart.github.io/vuex-pathify/#/api/accessors?id=get

So you could just put that code in a method.

If you want to use it directly, there is a workaround:

https://codesandbox.io/s/nk0oy7zmop

You need to:

1. Use `get()` in the methods block
2. Call `()(args)` on the returned function 

So it looks like I could improve on this in the core code, perhaps by if a function is detected, returning the function. I'll have to check the code to see if I did anything around this in the first place.

Let me know how you get on!

**Comment by davestewart** [comment]
Well the most concise way would probably be:

```js
postsByUser() {
    return this.$store.get("entity/post/getPostsByUser")(this.user.id);
}
```

**Comment by emcho92** [comment]
True, but I wanted to keep it as a computed prop, just made it easier as I was refactoring everything. I'll do another round of fine tuning as pathify is just now sinking in for me. Thanks!

**Comment by davestewart** [comment]
> True, but I wanted to keep it as a computed prop

You should be able to create it as a computed prop too:

- https://codesandbox.io/s/932nvokz0p
