### ISSUE TITLE
call naming

### ISSUE THREAD

**Issue by ozum** [davestewart/vuex-pathify#39]
Hi,

When I use default `makeActions(state)`, using `call` with `name` throws error, but with `setName` it works.

Please see, example below. I expected `this.localeA("en")` works, but it throws error.

**store**
```js
const state = { locale: "en" };
const actions = makeActions(state);
```

**component**
```js
methods: {
  localeA: call('locale'),  // unknown action type: locale
  localeB: call('setLocale') // sets locale
}
```

I assumed from documentation to be used like `get("locale")`, `sync("locale")`, `call("locale")`.

Am I correct?

**Comment by davestewart** [comment]
So the `make.*` helpers are designed around setting / getting data; essentially, converting store property `name`s to either `commit` or `dispatch` paths:

```
foo => setFoo()
```

See:

- https://davestewart.github.io/vuex-pathify/#/setup/install?id=config

However, `call()` is designed to wrap a dispatch (any dispatch, not necessarily a `make`ed action) with a convenience wrapper:

```
foo -> foo()
setFoo -> setFoo()
loadFoo -> loadFoo()
```

So they are not connected.

If you think the docs are ambiguous, let me know and I will fix them!

**Comment by davestewart** [comment]
OK, thanks for your thoughts.

I'm reluctant to expand on the table in the intro as I want to keep it as simple as I can to communicate the main concept...

...but I see your points in relating the functionality from a different part of the lib. I'll try to think how I can do it differently!

**Comment by ozum** [comment]
Maybe, you could add table in a subpage to keep intro simple and provide a full ref in a sub page.
