### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by GMaiolo** [davestewart/vuex-pathify#4]
Are unit tests in the roadmap?

**Comment by davestewart** [comment]
They sure are.

There's too much going on under the hood to remain untested!

Got any recommendations on testing frameworks / setup?

**Comment by hlobil** [comment]
I would recommend Jest ...

**Comment by davestewart** [comment]
Thanks, I'll look into that.

**Comment by davestewart** [comment]
Have started writing tests :)

**Comment by imyjimmy** [comment]
Hi Dave,

Any updates on this? Our team is having trouble accessing a mock store with pathify syntax in jest unit tests: 

`TypeError: wrapper.vm.$store.set is not a function`
`> 109 |     wrapper.vm.$store.set('activated/activeQpiCategoryList', ['1','2'])`

We've made sure to include pathify in the mockStore ([see gist](https://gist.github.com/imyjimmy/e583505e05528f213dd55bfa08b02499)) and we're using `createStoreMocks`, defined in our mockStore, in our spec ([another gist](https://gist.github.com/imyjimmy/d46eba96abf92930d13a98a54183fce7))

Thanks,

Jimmy

**Comment by davestewart** [comment]
Hey Jimmy,

Actually, no, not started writing tests yet.

Let me look into this though. Do you think there's some way to change the setup of pathify to support tests (if it's not already?) ?

**Comment by rumanbsl** [comment]
A boilerplate of how to test vuex-component would be great when vuex-pathify is enabled!
