### ISSUE TITLE
"helpers/vuex.js" can not replaced at runtime

### ISSUE THREAD

**Issue by ZhijianZhang** [davestewart/vuex-pathify#42]
And i still can  not understand why this vuex object can be REPLACED AT RUNTIME WITH THE ACTUAL VUEX STORE

**Comment by ZhijianZhang** [comment]
```
// helpers/component.js

export function get(path, props) {
  return make(path, props, getOne, function (path) {
   return expandGet(path, vuex.store.state, vuex.store.getters)
  })
}
```
the second and the third param of the function named expandGet, you use `vuex.store.xxx`, and the `vuex` obj here is comed from `helpers/vuex.js` which is created by youself. 

i saw the annotation " this object is replaced at runtime with the actual vuex store. ", but in fact, i always get vuex is undefined when i used. so i just can not understand why this vuex object can be replaced.

sorry my poor english.

**Comment by ZhijianZhang** [comment]
maybe i should pay more attention  to the files "helpers/accessers.js" and "plugin/pathify.js"

**Comment by davestewart** [comment]
Ah, now I understand why you were typing in capitals!

From here:

- https://github.com/davestewart/vuex-pathify/blob/develop/src/helpers/vuex.js

### Explanation

So the plugin needs to some acrobatics to get a reference to Vuex, so it can work directly on it.

This is accomplished in the install function:

- https://github.com/davestewart/vuex-pathify/blob/develop/src/plugin/pathify.js

It first imports an Object called `vuex`, and on this object is a property `store`.

In the install function, the Vuex instance is passed in (this is just how Vue does it) and that is added to the `vuex` instance which is part of Pathify.

The reason for this that then other parts of pathify can also import `vuex` and access the `store` property, which will be the same global Vuex you access via `import store from 'store' ...` or  in components `this.$store...`. All three references point to the same store, the one you as a developer declare in your project.

The reason for this, is that certain functions won't have access to the component `this` so won't be able to reference `this.$store` so they grab the helper reference to it.

The reason for the "dummy" code is with the capital letters is for code intelligence when I am authoring the plugin.


### Your issue

So - still not totally sure if you have a problem, or you are just curious how it works?

Are you having a problem that is preventing you from using Pathify?

Is this a `question` or a `bug` ?

😃

**Comment by ZhijianZhang** [comment]
I got it. I have learned a lot from your code ,Thank you very much ~
