### ISSUE TITLE
Nuxt 3 Vuex workaround

### ISSUE THREAD

**Issue by chiboreache** [davestewart/vuex-pathify#44]
Hi!
Since Nuxt 2 already warning us about deprecating [classic way](https://nuxtjs.org/guide/vuex-store#activate-the-store) of doing Vuex, so my question is:

how to make neat `store.set('foo/bar')` work again 
without `import store from './store/index'` ?

**Comment by davestewart** [comment]
What's their new plan?

**Comment by davestewart** [comment]
I asked a question here:

https://cmty.app/nuxt/nuxt.js/issues/c8589

**Comment by chiboreache** [comment]
lol

you have to enabling plugins in `nuxt.config.js` in `plugins: []`

> their new plan
is to make it nice and clean, obviously heh

> Modules: every .js file inside the store directory is transformed as a namespaced module (index being the root module).
> The store will be created as such: blah-blah
go through the link above

**Comment by davestewart** [comment]
OK, so as long as the plugin's `install()` method is called, passing an instance of `store`, it should just work:

- https://github.com/davestewart/vuex-pathify/blob/develop/src/plugin/pathify.js
- https://github.com/davestewart/vuex-pathify/blob/develop/src/helpers/accessors.js

**Comment by davestewart** [comment]
@chiboreache - did you have any more info on this? Is this still an issue I need to handle?

**Comment by chiboreache** [comment]
I just got bogged down in routine *(and python)*, sorru =)

but I'm finally back, and I already tired from getters and mappers, so yeah, I will dig in at this week :100:

**Comment by davestewart** [comment]
I know the feeling! (of getting bogged down)

**Comment by chiboreache** [comment]
**LOL**

i fixed it.

![Screenshot_20190323_163300](https://user-images.githubusercontent.com/16459251/54866829-d91e2300-4d89-11e9-8d51-d3840bbe1153.png)

**Comment by chiboreache** [comment]
but there is an error in 2.4 version _(with 1.4 from example project all fine)_


so yeah, that wasn't hard, heh:

```js
import pathify from 'vuex-pathify'
import hello from './modules/hello'

console.log('STORE FILE LOADED!')

export const plugins = [ pathify.plugin ]
export const modules = { hello }
export const actions = {
  nuxtServerInit(context, value) {
    console.log('NUXT_SERVER_INIT!')
  }
}
```

this is thrue **Module mode** index.js ;)

I can pr you fully loaded coffeescript variant, just a little bit later =)

**Comment by davestewart** [comment]
So what was the final conclusion?

Does Pathify need updates to code or docs?

**Comment by chiboreache** [comment]
Yeah, of course it would be nice, since Nuxt would be going that(modules) way.

When I finally figuring out how to PR poreply, I will push you coffee example ;)

**Comment by imranaalam** [comment]
is this being used with NUXT? as of today. new NUXT with vue 3 is releasing today...

**Comment by davestewart** [comment]
Not sure. I'll reopen the issue...
