### ISSUE TITLE
How to extend Vue.prototype with Pathify helper functions?

### ISSUE THREAD

**Issue by Zireael** [davestewart/vuex-pathify#49]
Hi,
I'm trying to register Pathify helper functions globally in Vue instance so they are available in all components, but I'm getting the function text printout as output instead of invoking it.
I'm trying to do it with a plugin install like so:

```
import { get, set, sync, call } from "vuex-pathify";

export default {
  install(Vue, options) {
    Vue.prototype.$myget = get
    Vue.prototype.$myset = set
    Vue.prototype.$mysync = sync
    Vue.prototype.$mycall = call
  }
};
```
When I try to do in a component:
`var someVar = this.$myget("colours.colourForeground");`

I'm getting function text string

```
ƒ () {
    var args = [], len = arguments.length;
    while ( len-- ) args[ len ] = arguments[ len ];

    if (!this.$store) {
      throw new Error('[Vuex Pathify] Unexpected condition: this.$store is…
```
I tried invoking get in a wrapper with argument passing like ` Vue.prototype.$myget: (arg) => get(arg)`, but no luck.
If I hardcode the argument 
`Vue.prototype.$myget = get("colours.colourForeground")`
 I receive correct expected output (works as expected).
Should I be binding the get/set/etc first and doing `this.get` etc in plugin install? Couldn't get that to work either. I'd appreciate your advice.
Would global mixin be better idea?

Thanks in advance

**Comment by shreeve** [comment]
Vue.prototype.$set is already defined. You need to pick another name than
$set.

**Comment by Zireael** [comment]
> Vue.prototype.$set is already defined. You need to pick another name than $set.
My bad, fixed main post. I was actually testing with naming schema like $getx on my machine, just cleaned the code for posting here. The initial question still stands :)

**Comment by davestewart** [comment]
Hi @Zireael,

Sorry to leave it so long to get to this!

My guess is that `this` is pointing to the wrong place, or you've not `use`d Vuex at that point.

If you stick a breakpoint in there, what is `this` ?

**Comment by davestewart** [comment]
By the way - I've just realised, that even if you do this, you won't be able to use the functions as you want.

When you declare your component definition, `Vue.prototype` does't yet exist:

```js
import { sync } from 'vuex-pathify'
export default {
  computed: sync ( ... ) // <- at this point, `this` does not exist!
}
```

So you won't be able to do this:

```js
export default {
  computed: this.sync ( ... ) // :( sad face
}
```

**Comment by Zireael** [comment]
That was a neat bind idea. Bummer! I was trying to go lazy and not have to bind helpers in every component. No biggie, I was just curious why it wasn't working for me (great learning opportunity) - thanks for explanation!
I'll try doing a mixin into main Vue instance - that should work (maybe).

**Comment by davestewart** [comment]
Pathify is lazy anyway, so it's lazy * lazy :P
