### ISSUE TITLE
How to reference this (Vue instance) 

### ISSUE THREAD

**Issue by haexhub** [davestewart/vuex-pathify#62]
Hi,

I would like to know, how to refer to the Vue instance in computed properties.

this works
``` javascript
  computed: {
    menu: sync('fancy_module/menus@navigation.items')
  }
```

this not
``` javascript
  data () {
    return {
      foobar: 'fancy_module/menus@navigation.items'
    }
  }

, computed: {
    menu: sync(this.foobar)
  }
```
**this** is not referencing to Vue. 
I know that arrow functions bring a new this context. But I don't use it here, do I?
Any advie would be great.

**Comment by davestewart** [comment]
Hey @haexhub 

This seems to come up a lot, so I'll probably add some documentation on how to handle this.

In the meantime, see this issue and the comments / links:

https://github.com/davestewart/vuex-pathify/issues/28

I think I might add a helper as well, so this kind of thing is easy.
