### ISSUE TITLE
Can't find Mutations in Vue devtools

### ISSUE THREAD

**Issue by abelland** [davestewart/vuex-pathify#65]
Hi,
given a simple store that looks like this

```
import { make } from 'vuex-pathify'

const state = () => {
  return {
    user: {}
  }
}
const mutations = {
  ...make.mutations(state)
}

export default {
  namespaced: true,
  state,
  mutations
}
```

and a component that looks like this

```
<template>
  <input v-model="user.username">
  <p>User is: {{ user.username }}</p>
</template>

<script>
import { sync } from "vuex-pathify";

export default {
  name: "app",
  computed: {
    ...sync("user/user)
  }
};
</script>
```

when I write something inside my input everything works as expected, but when I'm looking at vue dev tools the expected mutation SET_USER does not showing up in the Vuex section

what am I missing?

**Comment by davestewart** [comment]
Hi,

And sorry for the wait! I didn't see this.

Looks like you are referencing `username` in your component, but the store expects `user/user`.

Get that right and you should see the appropriate mutations.
