### ISSUE TITLE
Sync doesn't work with dynamic modules registered w/ Vuex's registerModule

### ISSUE THREAD

**Issue by JessicaSachs** [davestewart/vuex-pathify#74]
When I use dynamic modules, `sync` breaks. :-(

Here's the [example repo](https://github.com/JessicaSachs/vuex-pathify-bug)...
And [here's the line](https://github.com/JessicaSachs/vuex-pathify-bug/blob/master/pages/index.vue#L16) that I think should be working but isn't.

A short example, assuming that the store is properly implemented, looks like this:

```javascript
export default {
    computed: {
        foo: get('topLevel/myDynamicModule/foo'), // works
        // foo: sync('topLevel/myDynamicModule/foo'), // broken
    },
    beforeCreate() { this.$store.registerModule('topLevel/myDynamicModule', MyDynamicStore); }
}
```

**Comment by davestewart** [comment]
Cool - so had a quick look at this, just to verify.

I checked to see if the latest updates caused this, but it looks like 1.2 shows the same behaviour.

At work today, so I'll dive in when I get home later.

**Comment by davestewart** [comment]
Just read my own docs again, and I think this might already be solved.

Did you read this section?

- https://davestewart.github.io/vuex-pathify/#/api/component?id=dynamic-module-registration

I realise there is a lot to read, because I try to explain everything 😬

**Comment by JessicaSachs** [comment]
Ah, this seems to have fixed it! Thank you.
