### ISSUE TITLE
Can't make vuex-pathify work with vue-class-decorator

### ISSUE THREAD

**Issue by garyo** [davestewart/vuex-pathify#75]
I'm trying to create a class-style component, in typescript:
```ts
<script lang="ts">
import 'reflect-metadata'
import { Component, Prop, Vue } from 'vue-property-decorator'
import { sync } from "vuex-pathify";

@Component({
  computed: {
    ...sync('*')
  }
})
export default class HelloWorld extends Vue {
  @Prop() private msg!: string;
}
</script>
```

but the line where I add `...sync('*')` to the component options causes the following error:
```
39:2 No overload matches this call.
  Overload 1 of 2, '(options: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>> & ThisType<Vue>): <VC extends VueClass<...>>(target: VC) => VC', gave the following error.
    Type '{ get: GetAccessor<any>; set: SetAccessor<any>; }' is not assignable to type 'Accessors<DefaultComputed>'.
      Property 'set' is incompatible with index signature.
        Type 'SetAccessor<any>' is not assignable to type 'ComputedOptions<any> | (() => any)'.
          Type 'SetAccessor<any>' is not assignable to type '() => any'.
  Overload 2 of 2, '(target: VueClass<Vue>): VueClass<Vue>', gave the following error.
    Argument of type '{ computed: { get: GetAccessor<any>; set: SetAccessor<any>; }; }' is not assignable to parameter of type 'VueClass<Vue>'.
      Object literal may only specify known properties, and 'computed' does not exist in type 'VueClass<Vue>'.
```

I'm not sure what I'm doing wrong.

**Comment by garyo** [comment]
I saw a note in the source about `sync`  type definitions not supporting wildcards so I tried a few other sets of args to the `sync()` call: `sync(['foo', 'bar'])` and even `sync()` but those didn't help.

**Comment by garyo** [comment]
Also tried it without `vue-class-decorator`, same errors:
```
<script lang="ts">
import Vue from 'vue'
import { sync } from 'vuex-pathify'

export default Vue.extend({
  name: 'HelloWorld',
  props: {
    msg: String
  },
  computed: {
    ...sync('*')
  }
})
</script>
```

**Comment by garyo** [comment]
Aha, I just read https://forum.vuejs.org/t/vuex-pathify-1-2-now-has-typescript-typings-and-decorators/58621 -- you have to replace `sync` with `Sync` if using Typescript, it appears.
An update to the README would save folks like me some hair-pulling...

**Comment by davestewart** [comment]
Sorry about that!

I've added a warning so hopefully yours will the last hair-pulled for this issue :P

**Comment by garyo** [comment]
One further note: Sync() only accepts one single property, whereas sync('*') allows access to all the props and sub-props. So unless I misunderstand things, Sync() seems a lot less useful because it doesn't allow you to access/update sub-props using pathify style. I'd have to Sync() each individual prop of each class, right?

**Comment by davestewart** [comment]
That's right.

> They are [single-property-access](api/component?id=single-property-access) equivalents of their [component helpers](api/component) counterpart.

It's possibly clear to some, but not others.

Maybe I should add a small "differences" section...

**Comment by garyo** [comment]
So if you're using Typescript, you can't use vuex-pathify to get two-way path-style access to your objects.

**Comment by davestewart** [comment]
Not sure I understand?

You can use `sync` but you need to set up individual properties due to the way decorators work.

Saying that, it might be possible to make this work.

Let me look into it (this code was written by another developer) but I did some stuff with decorators about 9 months ago and it was pretty straightforward.

**Comment by lynx-r** [comment]
> Also tried it without `vue-class-decorator`, same errors:
> 
> ```
> <script lang="ts">
> import Vue from 'vue'
> import { sync } from 'vuex-pathify'
> 
> export default Vue.extend({
>   name: 'HelloWorld',
>   props: {
>     msg: String
>   },
>   computed: {
>     ...sync('*')
>   }
> })
> </script>
> ```

I'd like to notice that you can solve the typings error by specifying a type of `sync` like `sync<any>` or `sync<YourStoreType>`.
