### ISSUE TITLE
make.mutations ignores pathify.options

### ISSUE THREAD

**Issue by disarticulate** [davestewart/vuex-pathify#8]
Do as follows:

```
import pathify from 'vuex-pathify'

// options
pathify.options.mapping = 'simple'
pathify.options.deep = false

export default pathify
```
then make.mutations
```
import { make } from 'vuex-pathify'
import state from './state'
make.mutations(state)
```
Expected behavior:

state -> mutation : foo -> foo

Actual behavior

foot -> SET_FOO

**Comment by davestewart** [comment]
OK, the new demo is up at:

- https://github.com/davestewart/vuex-pathify-demos/tree/master/simple

You can run it online at:

- https://codesandbox.io/s/github/davestewart/vuex-pathify-demos/tree/master/simple?module=%2Fsrc%2Fstore%2Fpathify.js

This is the `standard` naming scheme running:
 
![image](https://user-images.githubusercontent.com/132681/39873959-54654428-5464-11e8-9374-641fdc31f13f.png)

This is the `simple` naming scheme running:

![image](https://user-images.githubusercontent.com/132681/39874009-75638c98-5464-11e8-8daa-f85b9284aced.png)

Have a look and let me know.

**Comment by disarticulate** [comment]
My project structure technicall prevents it.

i've got the following store:

- store
  - module 1
  - module 2
index.js

Each module does:
```
import state from './state'
import * as getters from './getters'
import * as mutations from './mutations'
import * as actions from './actions'

import { make } from 'vuex-pathify'

export default {
  namespaced: true,
  state,
  getters: Object.assign(make.getters(state), getters),
  mutations: Object.assign(make.mutations(state), mutations),
  actions
}
```
So I can't set the options in the root:
```
import Vue from 'vue'
import Vuex from 'vuex'

import main from './main'
import identity from './module1'
import dataTable from './module2'
import pathify from './_pathify'

Vue.use(Vuex)

const store = new Vuex.Store({
  plugins: [ pathify.plugin ],
  modules: {
    main,
    identity,
    // dataTable,
    persistence
  }
})

export default store
```

You may want to look at a constructor perhaps?

then it'd be:
```
import Pathify from 'vuex-pathify'
pathify = new Pathify()
```

**Comment by davestewart** [comment]
So what's to prevent you from the pathify import before the main import?

**Comment by disarticulate** [comment]
it's ambiguous which module gets imported first, i guess. I don't know well enough about the import system, but if I assumed it was the first module, then I'd put it there. But relying on unstated or poorly formed implicit binding seems a bad idea for me.

**Comment by disarticulate** [comment]
I'm looking right now on what'd be required to make a constructor

**Comment by davestewart** [comment]
> it's ambiguous which module gets imported first, i guess

You guess, or you know?

I haven't had any problems so far.

If you want to make sure, I imagine that you could always import pathify and set its options in each module.

**Comment by davestewart** [comment]
By the way, why do you think `new Pathify()` would fix it?

I think perhaps that imports are hoisted so that might be irrelevant.

**Comment by disarticulate** [comment]
You can close this ticket as resolved. It likely works as you described. But I think you'll run into more issues if a user has to figure out where the _first_ usage of the import is.

Because a constructor will determine exactly where the entry point is. The way you've got this structured, you have two components:
- Make
- Make setters

both relying on an options object which you're importing into each module. This is what the constructor is suppose to be for.

**Comment by disarticulate** [comment]
here's what a constructor would look like:
```
class Pathify {

  constructor(userOptions=options) {
    import accessorize from '../helpers/accessors'
    import options from './options'
    import debug from './debug'
    this.options = Object.assign(options, userOptions)
    this.debug = () => debug(this.options)
    this.plugin = (store) => {
      vuex.store = store
      accessorize(store, options)
    }
  }
  makeActions (state) {
    return getStateKeys(state)
      .reduce(function (obj, key) {
        const action = resolveName('actions', key, this.options)
        const mutation = resolveName('mutations', key, this.options)
        obj[action] = function ({commit}, value) {
          commit(mutation, value)
        }
        return obj
      }, {})
  }
}
```
```
// resolver.js
export function resolveName (type, name, options) { ... }
export function resolve (store, path, options) { ... }
```

**Comment by disarticulate** [comment]
this is what it'd look like, roughly.

https://github.com/disarticulate/vuex-pathify

**Comment by davestewart** [comment]
> But I think you'll run into more issues if a user has to figure out where the first usage of the import is

Well you just import Pathify and set the options in your project's entry point ie. `main.js` and you're covered.

I think the constructor idea probably won't work project-wide (at least easily) as Pathify's options needs to be global. The reason for this is that state names are converted for store setup (`make.*`) AND store access (`get/set/sync()`, `store.get/set/copy()`)

Because global access goes through a single point, you aside from creating a new instance for each store, each would each need to be the same, as would the global configuration.

All in all it adds up to lots of new code, all over the place.

If a problem crops up, I'll address it, but re-setting the options I think will be the simplest solution.

Closing for now, but if you think I'm missing something, do let me know.

**Comment by disarticulate** [comment]
This works fine, I think I was just having a brain fart. Here's my store:
```
import Vue from 'vue'
import Vuex from 'vuex'

import pathify from './_pathify'

import main from './main'
import identity from './identity'
import dataTable from './dataTable'
import persistence from './persistence'

Vue.use(Vuex)

const store = new Vuex.Store({
  plugins: [ pathify.plugin ],
  modules: {
    main,
    identity,
    // dataTable,
    persistence
  }
})

export default store
```

Moving the module import with the pathify options solves the loading issue. Just seems a bit awkward to see the options go into semantically unrelated imports (make & pathify). I'm sure if I come back to this in a year I'll have no idea how this magic works.

**Comment by davestewart** [comment]
Hmm, OK.

So I thought I would have solved any conceptual issues around this through clear documentation:

- https://davestewart.github.io/vuex-pathify/#/setup/config?id=config

Do you have any opinion on what or how they're written / structured?

Could they be clearer / more helpful / more explicit ?

**Comment by disarticulate** [comment]
Then:
```
//module 1
import state from './state'
import * as getters from './getters'
import * as mutations from './mutations'
import * as actions from './actions'

import { make } from 'vuex-pathify'

export default {
  namespaced: true,
  state,
  getters: Object.assign(make.getters(state), getters),
  mutations: Object.assign(make.mutations(state), mutations),
  actions
}
```

**Comment by davestewart** [comment]
>   getters: Object.assign(make.getters(state), getters),

Making redundant getters is actually not required, as Pathify will determine to get from state or getters automatically. The functionality is there for those who REALLY want to, but IMHO it just adds more code to run, and clogs up the Vue DevTools panel anyway.

Therefore you could just pull in `make` in your `mutations.js` file.

**Comment by disarticulate** [comment]
I'm avoiding looking at my code getters and seeing what the difference is. Some of them may be reducing state but may have a standard name.

This means I might have some redundancy I can clean up, but it also doesn't break anything if I add it this way to any module.

If I were starting a new project, I'd probably do as you suggest. Just how I have it setup so I don't have to worry about some non-standard getter with name conflict
