### ISSUE TITLE
Using Component Props inside get()

### ISSUE THREAD

**Issue by devtobi** [davestewart/vuex-pathify#86]
I’m currently having the problem, that a component should get data from different store modules depending on a given property.
Since I cant use „this“ inside get() I found variable expansion principle.
However, I cant get it to work...
Is this even possible?
If yes, could you provide an example?

Thanks in advance,
Keep up the good work!

**Comment by davestewart** [comment]
Hello!

Yes, you can use the new "variable expansion" feature:

- https://davestewart.github.io/vuex-pathify/#/api/paths?id=variable-expansion

```js
computed: {
  get ('module/:prop@value')
}
```

Or do it manually:

```js
computed:{
  value () {
    return this.$store.get(`module/${this.prop}@value`)
  }
}
```

Does that help?

**Comment by devtobi** [comment]
I`d like to use the property as a placeholder for the store module used in the get call:
e.g.

```
data() {
    return {
      module: "testmodule"
    };
},
computed: {
    items: get(":mode/items"),
}
```

however this is not working...
The manual approach does not work too.

I get the error: ``undefined has no properties``

**Comment by davestewart** [comment]
Well you have module and mode so that's not going to work.

**Comment by devtobi** [comment]
Ah I´m sorry. Of course it must be module in data and in the get function. However it does still not work

**Comment by davestewart** [comment]
I think the best thing to do here would be to post a demo showing what doesn't work and what you are trying, then we can go from there:

- https://codesandbox.io/s/github/davestewart/vuex-pathify-demos/tree/master/simple

**Comment by devtobi** [comment]
Already managed to get it to work, thanks anyways 😄

**Comment by w3llcod3** [comment]
Hi @devtobi 

How did you manage to solve the dynamic module name please? I'm stuck in same issue.

**Comment by devtobi** [comment]
> Hi @devtobi 
> 
> 
> 
> How did you manage to solve the dynamic module name please? I'm stuck in same issue.

Im sorry to say, but unfortunately I don't have access to the codebase anymore so I cannot look it up.

**Comment by w3llcod3** [comment]
> > Hi @devtobi
> > How did you manage to solve the dynamic module name please? I'm stuck in same issue.
> 
> Im sorry to say, but unfortunately I don't have access to the codebase anymore so I cannot look it up.

That's unfortunate 😥.  I guess I'll open new thread. Thanks anyway.
