### ISSUE TITLE
1.4.1 not released to github

### ISSUE THREAD

**Issue by jcoby** [davestewart/vuex-pathify#90]
**Describe the bug**
1.4.1 has been released to npm but a release and changelog has not been added here. Doing a package diff shows it to be related to #77 and fixes #59 so it'd be nice to have github updated.

**Expected behaviour**
1.4.1 to show up in the changelog and releases page. `package.json` updated to have latest version.

**Comment by davestewart** [comment]
Sorry about that. Away on holiday at the moment. Will update in a couple of weeks

**Comment by vesper8** [comment]
any update on this @davestewart ?

**Comment by davestewart** [comment]
Just got back from another trip! I'll do it now :)

**Comment by davestewart** [comment]
Done
